export interface State {
  patients: Patient[],
  patient: Patient,
  parameters: RequestPatient
}

export interface RequestPatient {
  page?: number
  size?: number
  paciente_nome: string,
  id_corp?: number
}

export interface Patient {
  id: number
  id_plano: number
  patient: {
    id: number,
    nome: string,
    ativo: boolean,
    cargo: string,
    salario: string | number | null,
    matricula: string | number | null,
    id_plano: string | number | null,
    horasextras: string | number | null,
    id_setor: string | number | null,
    endereco: string,
    tel_comercial: string,
    cep: string,
    tel_residencial: string,
    tel_celular: string,
    tel_outro: string,
    cpf: string,
    data_nasc: string,
    sexo: string,
    rg: string,
    id_medicos: string | number | null,
    cartao_nacional: string | null,
    id_tipo: number,
    prontuario_antigo: number | string,
    data_obito: string | null,
    foto: string | null,
    e_mail: string,
    responsavel: string,
    obs: string,
    medico_indica: string | null,
    data_admissao: string | null,
    id_empresa: string | null,
    cpts: string | null,
    livro_registro: string | null,
    ramal: string | null,
    unificado: string | null,
    data_gravacao: string,
    esterno: boolean,
    usuario: string,
    cidade: string,
    bairro: string,
    id_corp: number | string,
    confir_consulta: string | number,
    id_raca: number,
    id_etnia: number,
    nome_mae:  string,
    eletronico: string | null,
    id_escolaridade: 0,
    pai:  string,
    id_estado_civil: number,
    natural_de: string,
    id_religiao: number,
    ncasa:  string,
    uf: string,
    indicado_paciente: string | null,
    data_morigem: string | null,
    id_medico_equipe: string | null,
    senha: string | null,
    id_user: number,
    id_responsavel: string | null,
    n_pis: string | null,
    id_orgao: number,
    id_pais: number,
    id_uf: number,
    id_uf_ctps: number,
    id_uf_naturalidade: number,
    id_uf_documento: number,
    uf_naturalidade: null,
    complemento_endereco: string | null,
    escola: boolean,
    nome_documento: string,
    secao_titulo_eleitor: string | null,
    zona_titulo_eleitor: string | null,
    titulo_eleitor: string | null,
    numero_livro_registro: string | null,
    tipo_certidao: string | number,
    numero_folha_registro: number | null,
    numero_termo_registro: number | null,
    nome_cartorio: string | null,
    emissao_certidao: string | null,
    uf_ctps: string | null,
    emissao_ctps: string | null,
    serie_ctps: string | null,
    cbo: string | null,
    tipo_endereco: string | null,
    data_entrada_brasil: string | null,
    pais_origem: string | null,
    nacionalidade: string | null,
    data_documento: string | null,
    orgao_documento: string | null,
    complemento_documento: string | null,
    uf_documento: string | null,
    id_cbo: string | null,
    recem_nascido: boolean,
    hash: string,
    data_acesso_app: string | null,
    ultimo_acesso_app: string | null,
    validade_senha_app: string | null,
    senha_app_temp: string | null,
    token: string | null,
  }
  matricula: string
  validade: string
  principal: boolean
  data_gravacao: string
  ativo: boolean
  id_corp: number
  id_user: number | string | null
}