export class Company {
    id : number
    nome : string
    cnpj : string
    crm : number
    cnes : string
    endereco : string
    tl : string
    numero : string
    complemento: string
    municipio : string
    uf : string
    cod_ibge : string
    cep : string
    tel_comercial : string
    tel_residencial : string
    tel_celular : string
    tel_outro : string
    id_cidade : number
    id_bairro : number
    fatura : boolean
    logomarca : string
    e_mail : string
    smtp : string
    senha : string
    smtp_porta : number
    e_mail_destino : string
    ism : boolean
    apelido : string
    id_corp : number
    contato : string
    id_user : number
    cidade : string
    bairro : string
    cf_df : string
    numero_nf_inicial : number
    numero_nf_final : number
    validade_nf : string
    inscri_estadual : string
    cod_unidade_federacao : number
    ch_consulta : number
    ch_sadt : number
    ch_hi : number
    ch_us : number
    retorno : number
    site : string
    regime_tributario : number
    cnae : string
    inscricao_municipal : string
    enviar_nfe : boolean
    certificado : string
    senha_certificado : string
    ativo : boolean
    csc : string
    id_responsavel : number
    certificado_serial : string
    validade_certificado : string
    certificado_revogado : boolean
    certificado_nome : string
    data_gravacao : string
    carga_tributaria : number
    modelo_exames : number
    modelo_venda : number
    json_google : string
    mp_access_token : string
    mp_client_id : string
    mp_client_secret : string
    mp_public_key : string
}