// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UseCombobox: typeof import('./components/base/combobox/useCombobox.ts')['default']
    UseDropdown: typeof import('./components/base/dropdown/useDropdown.ts')['default']
    VButton: typeof import('./components/base/button/VButton.vue')['default']
    VCombobox: typeof import('./components/base/combobox/VCombobox.vue')['default']
    VDropdown: typeof import('./components/base/dropdown/VDropdown.vue')['default']
    VEndStep: typeof import('./components/base/step/VEndStep.vue')['default']
    VFinder: typeof import('./components/base/finders/VFinder.vue')['default']
    VFullPagination: typeof import('./components/base/pagination/VFullPagination.vue')['default']
    VGroupButton: typeof import('./components/base/button/VGroupButton.vue')['default']
    VIconButton: typeof import('./components/base/button/VIconButton.vue')['default']
    VInput: typeof import('./components/base/form/VInput.vue')['default']
    VModal: typeof import('./components/base/modal/VModal.vue')['default']
    VMultiselect: typeof import('./components/base/selects/VMultiselect.vue')['default']
    VPagination: typeof import('./components/base/pagination/VPagination.vue')['default']
    VSelect: typeof import('./components/base/form/VSelect.vue')['default']
    VStepGroup: typeof import('./components/base/step/VStepGroup.vue')['default']
    VStepPanel: typeof import('./components/base/step/VStepPanel.vue')['default']
    VTable: typeof import('./components/base/table/VTable.vue')['default']
    VTableCell: typeof import('./components/base/table/VTableCell.vue')['default']
    VTimer: typeof import('./components/base/timer/VTimer.vue')['default']
  }
}

export {}
